project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "qmd/**/*.qmd"
    - "!DEV/"
    - "!asset/template/"
  resources:
    - "asset/img/"
    - "asset/js/"
    - "asset/style/"

website:
  title: "Demonax MMORPG"
  favicon: ""
  page-navigation: true

  navbar:
    background: dark
    logo: asset/img/logo.png
    title: false
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: qmd/about.qmd
      - text: "Getting started"
        href: qmd/getting_started.qmd
      - text: "Community"
        menu:
          - text: "Characters"
            href: qmd/community/characters.qmd
          - text: "Highscores"
            href: qmd/community/highscores.qmd
          - text: "Bestiary"
            href: qmd/community/bestiary.qmd
          - text: "Harvesting"
            href: qmd/community/harvesting.qmd
      - text: "Library"
        menu:
          - text: "Creatures"
            href: qmd/library/creatures.qmd
          - text: "Weapons"
            href: qmd/library/weapons.qmd
          - text: "Equipment"
            href: qmd/library/equipment.qmd
          - text: "Quests"
            href: qmd/library/quests.qmd
          - text: "Magic"
            href: qmd/library/magic.qmd
          - text: "Map"
            href: /map/index.html#32367,32239,7,3
            

  page-footer:
    left: ""
    center: ""
    right: ""

format:
  html:
    theme: cosmo
    page-layout: custom
    toc: false
    code-fold: false
    echo: false
    css: [asset/style/styles.css, asset/style/index.css]
    grid:
      body-width: 1400px
      sidebar-width: 0px
      margin-width: 50px

execute: 
  freeze: auto
